apiVersion: v1
kind: ConfigMap
metadata:
  name: green-promtail
  namespace: default
data:
  promtail.yml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: green-logs
              app: green # or planetarium?
              __path__: /logs/*.log
              namespace: default
