apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: latency-budget-burn
  labels:
    release: prometheus
spec:
  groups:
    - name: SLOs-http_server_requests_seconds
      rules:
        - alert: LatencyBudgetBurn 2 Days window
          annotations:
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"

          ##
          ## Convert failure rate to percentage and compared against .1% multiplied by the burn-rate value
          ## Alert fires if the failure rate is greater than burn-rate multiplied by the allowed failure rate
          ##

          expr: |
            (
            100 * latencytarget:http_server_requests_seconds:rate5m{job="planetarium-app"}
            > (14.4 * 0.1)
            )
            and
            (
            100 * latencytarget:http_server_requests_seconds:rate1h{job="planetarium-app"}
            > (14.4 * 0.1)
            )
          for: 2m
          labels:
            job: planetarium-app
            severity: critical

        - alert: LatencyBudgetBurn 5 Days window
          annotations:
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            (
            100 * latencytarget:http_server_requests_seconds:rate30m{job="planetarium-app"}
            > (6 * 0.1)
            )
            and
            (
            100 * latencytarget:http_server_requests_seconds:rate6h{job="planetarium-app"}
            > (6 * 0.1)
            )
          for: 15m
          labels:
            job: planetarium-app
            severity: critical

        - alert: LatencyBudgetBurn 10 Days window
          annotations:
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            (
            100 * latencytarget:http_server_requests_seconds:rate1d{job="planetarium-app"}
            > (3 * 0.1)
            )
            and
            (
            100 * latencytarget:http_server_requests_seconds:rate2h{job="planetarium-app"}
            > (3 * 0.1)
            )
          for: 1h
          labels:
            job: planetarium-app
            severity: warning

        - alert: LatencyBudgetBurn 30 Days window
          annotations:
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            (
            100 * latencytarget:http_server_requests_seconds:rate3d{job="planetarium-app"}
            > (0.1)
            )
            and
            (
            100 * latencytarget:http_server_requests_seconds:rate6h{job="planetarium-app"}
            > (0.1)
            )
          for: 3h
          labels:
            job: planetarium-app
            severity: warning

          ##
          ## Returns the failure rate of responses that are greater than 89ms response time
          ##

        - expr: |
            (
            1 - (sum(rate(http_server_requests_seconds_bucket{job="planetarium-app", code!~"5..", le="0.089478485"}[5m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[5m])))
            )
          labels:
            job: planetarium-app
          record: latencytarget:http_server_requests_seconds:rate5m

        - expr: |
            (
            1 - (sum(rate(http_server_requests_seconds_bucket{job="planetarium-app", code!~"5..", le="0.089478485"}[30m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[30m])))
            )
          labels:
            job: planetarium-app
          record: latencytarget:http_server_requests_seconds:rate30m

        - expr: |
            (
            1 - (sum(rate(http_server_requests_seconds_bucket{job="planetarium-app", code!~"5..", le="0.089478485"}[1h]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[1h])))
            )
          labels:
            job: planetarium-app
          record: latencytarget:http_server_requests_seconds:rate1h

        - expr: |
            (
            1 - (sum(rate(http_server_requests_seconds_bucket{job="planetarium-app", code!~"5..", le="0.089478485"}[2h]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[2h])))
            )
          labels:
            job: planetarium-app
          record: latencytarget:http_server_requests_seconds:rate2h

        - expr: |
            (
            1 - (sum(rate(http_server_requests_seconds_bucket{job="planetarium-app", code!~"5..", le="0.089478485"}[6h]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[6h])))
            )
          labels:
            job: planetarium-app
          record: latencytarget:http_server_requests_seconds:rate6h

        - expr: |
            (
            1 - (sum(rate(http_server_requests_seconds_bucket{job="planetarium-app", code!~"5..", le="0.089478485"}[1d]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[1d])))
            )
          labels:
            job: planetarium-app
          record: latencytarget:http_server_requests_seconds:rate1d

        - expr: |
            (
            1 - (sum(rate(http_server_requests_seconds_bucket{job="planetarium-app", code!~"5..", le="0.089478485"}[3d]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[3d])))
            )
          labels:
            job: planetarium-app
          record: latencytarget:http_server_requests_seconds:rate3d
