{
 "title": "Planetarium Burn Rate",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Burn Rate per Day ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", outcome=\"SERVER_ERROR\"}[1d])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burn Rate per 5 Days ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", outcome=\"SERVER_ERROR\"}[5d])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[5d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burn Rate per 5 Days ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", outcome=\"SERVER_ERROR\"}[15d])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[15d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burn Rate per 30 Days ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\", outcome=\"SERVER_ERROR\"}[30d])) / sum(rate(http_server_requests_seconds_count{job=\"planetarium-app\"}[30d]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}