apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-appdown
  labels:
    release: prometheus
spec:
  groups:
  - name: Green
    rules:
    - alert: AppDown
      expr: up{job="planetarium-app"} != 1
      labels:
        severity: critical
      annotations:
        summary: "App is down"
        description: "Prometheus has detected the application is not running"

    - alert: Latency 5m Interval
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[5m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[5m])) > .2
      labels:
        severity: critical
      annotations:
        summary: "Latency is over 200ms within 5m interval"
        description: "Prometheus has detected the application latency is over 200ms"     

    - alert: Success Rate 5m Interval
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[5m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[5m])) < .999
      labels:
        severity: critical
      annotations:
        summary: "Success rate is below 99.9% within 5m interval"
        description: "Prometheus has detected the application success rate is below 99.9%"