apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-high-memory-usage
  labels:
    release: prometheus
spec:
  groups:
    - name: High Memory Usage
      rules:
        ##
        ## Filtered twice, first by container name then pod name
        ## Memory usage for all 3 pods added is higher than ~1.12 GB
        ##
        - alert: High memory Usage 5m Interval
          expr: sum(container_memory_working_set_bytes{container="planetarium", pod=~"planetarium-deployment-blue.*"}) > 1200000000
          labels:
            severity: critical
          annotations:
            summary: "High memory Usage Detected"
            description: "Prometheus has detected one of the planetarium applications has High memory usage"
