apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-latency
  labels:
    release: prometheus
spec:
  groups:
  - name: Latency
    rules:
    - alert: Latency 5m Interval
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[5m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[5m])) > .2
      labels:
        severity: critical
      annotations:
        summary: "Latency is over 200ms within 5m interval"
        description: "Prometheus has detected the application latency is over 200ms"

    - alert: Latency 15m Interval
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[15m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[15m])) > .2
      labels:
        severity: critical
      annotations:
        summary: "Latency is over 200ms within 15m interval"
        description: "Prometheus has detected the application latency is over 200ms"

    - alert: Latency 30m Interval
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[30m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[30m])) > .2
      labels:
        severity: critical
      annotations:
        summary: "Latency is over 200ms within 30m interval"
        description: "Prometheus has detected the application latency is over 200ms"

    - alert: Latency 60m Interval
      expr: sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[60m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[60m])) > .2
      labels:
        severity: critical
      annotations:
        summary: "Latency is over 200ms within 60m interval"
        description: "Prometheus has detected the application latency is over 200ms"