apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-latency
  namespace: "default"
  labels:
    release: prometheus
spec:
  groups:
    - name: Latency
      rules:
        - expr: |
            sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[5m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[5m]))
          labels:
            job: planetarium-app
          record: latency:rate5m

        - expr: |
            sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[15m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[15m]))
          labels:
            job: planetarium-app
          record: latency:rate15m

        - expr: |
            sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[30m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[30m]))
          labels:
            job: planetarium-app
          record: latency:rate30m

        - expr: |
            sum(rate(http_server_requests_seconds_sum{job="planetarium-app"}[60m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[60m]))
          labels:
            job: planetarium-app
          record: latency:rate60m

        ############################
        ############################
        ## 99 Percentile Latency Recording Rules

        - expr: |
            histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job="planetarium-app"}[5m])))
          labels:
            job: planetarium-app
          record: latency99:rate5m

        - expr: |
            histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job="planetarium-app"}[15m])))
          labels:
            job: planetarium-app
          record: latency99:rate15m

        - expr: |
            histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job="planetarium-app"}[30m])))
          labels:
            job: planetarium-app
          record: latency99:rate30m

        - expr: |
            histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{job="planetarium-app"}[60m])))
          labels:
            job: planetarium-app
          record: latency99:rate60m
