apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-pod-restart
  labels:
    release: prometheus
spec:
  groups:
  - name: PodRestart
    rules:
    - alert: PodRestart 5m Interval 
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="default"}[5m])) > 1
      labels:
        severity: critical
      annotations:
        summary: "Pods are restarting more than once within 5m interval"
        description: "Prometheus has detected the cluster's pods are consistently restarting"

    - alert: PodRestart 15m Interval 
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="default"}[15m])) > 1
      labels:
        severity: critical
      annotations:
        summary: "Pods are restarting more than once within 15m interval"
        description: "Prometheus has detected the cluster's pods are consistently restarting"

    - alert: PodRestart 30m Interval 
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="default"}[30m])) > 1
      labels:
        severity: critical
      annotations:
        summary: "Pods are restarting more than once within 30m interval"
        description: "Prometheus has detected the cluster's pods are consistently restarting"

    - alert: PodRestart 60m Interval 
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="default"}[60m])) > 1
      labels:
        severity: critical
      annotations:
        summary: "Pods are restarting more than once within 60m interval"
        description: "Prometheus has detected the cluster's pods are consistently restarting"