apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-podsdown
  namespace: "default"
  labels:
    release: prometheus
spec:
  groups:
    - name: PodsDown
      rules:
        - alert: PodNotHealthy
          expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
          labels:
            severity: critical
          annotations:
            summary: One or more Pods are not healthy.
            description: "Pod is in a non-ready state."
