apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-success-rate
  labels:
    release: prometheus
spec:
  groups:
  - name: Success Rate
    rules:
    - alert: Success Rate 5m Interval
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[5m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[5m])) < .999
      labels:
        severity: critical
      annotations:
        summary: "Success rate is below 99.9% within 5m interval"
        description: "Prometheus has detected the application success rate is below 99.9%"

    - alert: Success Rate 15m Interval
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[15m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[15m])) < .999
      labels:
        severity: critical
      annotations:
        summary: "Success rate is below 99.9% within 15m interval"
        description: "Prometheus has detected the application success rate is below 99.9%"

    - alert: Success Rate 30m Interval
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[30m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[30m])) < .999
      labels:
        severity: critical
      annotations:
        summary: "Success rate is below 99.9% within 30m interval"
        description: "Prometheus has detected the application success rate is below 99.9%"

    - alert: Success Rate 60m Interval
      expr: sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[60m])) / sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[60m])) < .999
      labels:
        severity: critical
      annotations:
        summary: "Success rate is below 99.9% within 60m interval"
        description: "Prometheus has detected the application success rate is below 99.9%"