apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: planetarium-prometheus-rules-success-rate
  namespace: "default"
  labels:
    release: prometheus
spec:
  groups:
    - name: Success Rate
      rules:
        - expr: |
            sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[5m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[5m]))
          labels:
            job: planetarium-app
          record: successrate:rate5m

        - expr: |
            sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[15m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[15m]))
          labels:
            job: planetarium-app
          record: successrate:rate15m

        - expr: |
            sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[30m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[30m]))
          labels:
            job: planetarium-app
          record: successrate:rate30m

        - expr: |
            sum(rate(http_server_requests_seconds_count{job="planetarium-app", outcome!="SERVER_ERROR"}[60m]))
            /
            sum(rate(http_server_requests_seconds_count{job="planetarium-app"}[60m]))
          labels:
            job: planetarium-app
          record: successrate:rate60m
