apiVersion: "v1"
kind: "Service"
metadata:
  name: "planetarium-clusterip"
  namespace: "default"
  labels:
    app: planetarium
    role: blue # ${TARGET_ROLE}
    job: planetarium-app
spec:
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    app: "planetarium"
    role: "blue" # ${TARGET_ROLE}
  type: "ClusterIP"
