apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planetarium-service-monitor
  labels:
    release: prometheus
  namespace: default
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: planetarium
      job: planetarium-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
