apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: green-service-monitor
  labels:
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: green
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s