apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blue-service-monitor
  labels:
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: planetarium
      job: blue-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s
