{
 "title": "Planetarium Failure Rate",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failure Rate 5M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "latencytarget:http_server_requests_seconds:rate5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 30M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "latencytarget:http_server_requests_seconds:rate30m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 1H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "latencytarget:http_server_requests_seconds:rate1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 2H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "latencytarget:http_server_requests_seconds:rate2h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 6H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "latencytarget:http_server_requests_seconds:rate6h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 1D",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "latencytarget:http_server_requests_seconds:rate1d",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate per 3D",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "latencytarget:http_server_requests_seconds:rate3d",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Failure Rate 5M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count:burnrate5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 30M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count:burnrate30m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 1H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count:burnrate1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 2H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count:burnrate2h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 6H",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count:burnrate6h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 1D",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count:burnrate1d",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate 3D",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count:burnrate3d",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}