apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts
  labels:
    release: prometheus
  namespace: default
spec:
  groups:
    - name: blue-green-deployment
      rules:
        - alert: BlueDown
          expr: absent(up{job="blue-app"}) == 1
          labels:
            severity: critical
          annotations:
            summary: "Blue is down"
            description: "Prometheus has detected the application is not running"

        - alert: GreenDown
          expr: absent(up{job="green-app"}) == 1
          labels:
            severity: critical
          annotations:
            summary: "Green is down"
            description: "Prometheus has detected the application is not running"

    - name: SLO-threats
      rules:
        - alert: PodNotHealthy
          expr: kube_pod_status_phase{phase=~"Pending|Unknown|Failed|Terminating", namespace="default"} > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: One or more Pods are not healthy.
            description: "{{ $labels.pod }} is not healthy."

        - alert: PodRestart
          expr: changes(kube_pod_container_status_restarts_total{namespace="default"}[1m]) > 1
          labels:
            severity: critical
          annotations:
            summary: "Pods are restarting more than once within 5m interval"
            description: "{{ $labels.pod }} have restarted."

        - alert: PlanetariumDown
          expr: absent(up{job="planetarium-app"}) == 1
          labels:
            severity: critical
          annotations:
            summary: "Planetarium is down"
            description: "Prometheus has detected the application is not running"

        ##
        ## Filtered twice, first by container name then pod name
        ## Memory usage for all 3 pods added is higher than ~1.12 GB
        ##
        - alert: High memory Usage 5m Interval
          expr: memory-usage:blue > 1200000000
          labels:
            severity: critical
          annotations:
            summary: "High memory Usage Detected on Blue deployment"
            description: "Prometheus has detected one of the planetarium applications has High memory usage"

        ##
        ## Filtered twice, first by container name then pod name
        ## Avg cpu usage above indicated value
        ##
        - alert: High CPU Usage 5m Interval
          expr: cpu-usage:5m:blue > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Blue deployment"
            description: "Prometheus has detected one of the planetarium applications has High CPU usage"

        - alert: High CPU Usage 15m Interval
          expr: cpu-usage:15m:blue > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Blue deployment"
            description: "Prometheus has detected one of the planetarium applications has High CPU usage"

        - alert: High CPU Usage 30m Interval
          expr: cpu-usage:30m:blue > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Blue deployment"
            description: "Prometheus has detected one of the planetarium applications has High CPU usage"

        - alert: High CPU Usage 60m Interval
          expr: cpu-usage:60m:blue > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Blue deployment"
            description: "Prometheus has detected one of the planetarium applications has High CPU usage"

    - name: Green
      rules:
        ############################
        ############################

        - alert: Latency 5m Interval
          expr: |
            latency:rate5m{job="green-app"} > .2
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green latency is over 200ms within 5m interval"
            description: "Prometheus has detected the green application latency is over 200ms"

        - alert: Latency 15m Interval
          expr: |
            latency:rate15m{job="green-app"} > .2
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green latency is over 200ms within 15m interval"
            description: "Prometheus has detected the green application latency is over 200ms"

        - alert: Latency 30m Interval
          expr: |
            latency:rate30m{job="green-app"} > .2
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green latency is over 200ms within 30m interval"
            description: "Prometheus has detected the green application latency is over 200ms"

        - alert: Latency 60m Interval
          expr: |
            latency:rate60m{job="green-app"} > .2
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green latency is over 200ms within 60m interval"
            description: "Prometheus has detected the green application latency is over 200ms"

        ############################
        ############################

        - alert: Success Rate 5m Interval
          expr: |
            successrate:rate5m{job="green-app"} < .998
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green success rate is below 99.8% within 5m interval"
            description: "Prometheus has detected the green application success rate is below 99.8%"

        - alert: Success Rate 15m Interval
          expr: |
            successrate:rate15m{job="green-app"} < .998
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green success rate is below 99.8% within 15m interval"
            description: "Prometheus has detected the green application success rate is below 99.8%"

        - alert: Success Rate 30m Interval
          expr: |
            successrate:rate30m{job="green-app"} < .998
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green success rate is below 99.8% within 30m interval"
            description: "Prometheus has detected the green application success rate is below 99.8%"

        - alert: Success Rate 60m Interval
          expr: |
            successrate:rate60m{job="green-app"} < .998
          labels:
            job: green-app
            severity: critical
          annotations:
            summary: "Green success rate is below 99.8% within 60m interval"
            description: "Prometheus has detected the green application success rate is below 99.8%"

        ############################
        ############################
        ## Fires an alert when current memory usage is above ~384 MB

        - alert: High memory Usage
          expr: memory-usage:green > 400000000
          labels:
            severity: critical
          annotations:
            summary: "High memory Usage Detected on Green deployment"
            description: "Prometheus has detected one of the green app has High memory usage"

        ############################
        ############################

        - alert: High CPU Usage 5m Interval
          expr: cpu-usage:5m:green > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Green deployment"
            description: "Prometheus has detected one of the green app has High CPU usage"

        - alert: High CPU Usage 15m Interval
          expr: cpu-usage:15m:green > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Green deployment"
            description: "Prometheus has detected one of the green app has High CPU usage"

        - alert: High CPU Usage 30m Interval
          expr: cpu-usage:30m:green > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Green deployment"
            description: "Prometheus has detected one of the green app has High CPU usage"

        - alert: High CPU Usage 60m Interval
          expr: cpu-usage:60m:green > 0.15
          labels:
            severity: critical
          annotations:
            summary: "High CPU Usage Detected on Green deployment"
            description: "Prometheus has detected one of the green app has High CPU usage"
