apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: burn-rate
  labels:
    release: prometheus
  namespace: default
spec:
  groups:
    - name: SLOs-http_requests
      rules:
        - alert: ErrorBudgetBurn 2 Days window
          annotations:
            summary: "2% error budget consumption every 1 hour"
            description: "Failure rate of 2.88 or higher"
            message: "High error budget burn for job=planetarium-app (current value: {{ $value }})"

          ##
          ## Alert fires when failure rate is greater than burn-rate multiplied by the allowed failure rate
          ##

          expr: |
            http_server_requests_seconds_count:burnrate5m > (14.4 * 0.2)
            and
            http_server_requests_seconds_count:burnrate1h > (14.4 * 0.2)
          for: 2m
          labels:
            job: planetarium-app
            severity: critical

        - alert: ErrorBudgetBurn 5 Days window
          annotations:
            summary: "5% error budget consumption every 6 hours"
            description: "Failure rate of 1.2 or higher"
            message: "High error budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            http_server_requests_seconds_count:burnrate30m > (6 * 0.2)
            and
            http_server_requests_seconds_count:burnrate6h > (6 * 0.2)
          for: 15m
          labels:
            job: planetarium-app
            severity: critical

        - alert: ErrorBudgetBurn 10 Days window
          annotations:
            summary: "10% error budget consumption every 1 day"
            description: "Failure rate of 0.6 or higher"
            message: "High error budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            http_server_requests_seconds_count:burnrate2h > (3 * 0.2)
            and
            http_server_requests_seconds_count:burnrate1d > (3 * 0.2)
          for: 1h
          labels:
            job: planetarium-app
            severity: warning

        - alert: ErrorBudgetBurn 30 Days window
          annotations:
            summary: "10% error budget consumption every 3 days"
            description: "Failure rate of 0.2 or higher"
            message: "High error budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            http_server_requests_seconds_count:burnrate6h > (1 * 0.2)
            and
            http_server_requests_seconds_count:burnrate3d > (1 * 0.2)
          for: 3h
          labels:
            job: planetarium-app
            severity: warning

    - name: SLOs-latency
      rules:
        - alert: LatencyBudgetBurn 2 Days window
          annotations:
            summary: "2% error budget consumption every 1 hour"
            description: "Failure rate of 2.88 or higher"
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"

          ##
          ## Alert fires if the failure rate is greater than burn-rate multiplied by the allowed failure rate
          ##

          expr: |
            latencytarget:http_server_requests_seconds:rate5m > (14.4 * 0.2)
            and
            latencytarget:http_server_requests_seconds:rate1h > (14.4 * 0.2)
          for: 2m
          labels:
            job: planetarium-app
            severity: critical

        - alert: LatencyBudgetBurn 5 Days window
          annotations:
            summary: "5% error budget consumption every 6 hours"
            description: "Failure rate of 1.2 or higher"
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            latencytarget:http_server_requests_seconds:rate30m > (6 * 0.2)
            and
            latencytarget:http_server_requests_seconds:rate6h > (6 * 0.2)
          for: 15m
          labels:
            job: planetarium-app
            severity: critical

        - alert: LatencyBudgetBurn 10 Days window
          annotations:
            summary: "10% error budget consumption every 1 day"
            description: "Failure rate of 0.6 or higher"
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            latencytarget:http_server_requests_seconds:rate2h > (3 * 0.2)
            and
            latencytarget:http_server_requests_seconds:rate1d > (3 * 0.2)
          for: 1h
          labels:
            job: planetarium-app
            severity: warning

        - alert: LatencyBudgetBurn 30 Days window
          annotations:
            summary: "10% error budget consumption every 3 days"
            description: "Failure rate of 0.2 or higher"
            message: "High requests latency budget burn for job=planetarium-app (current value: {{ $value }})"
          expr: |
            latencytarget:http_server_requests_seconds:rate6h > (1 * 0.2)
            and
            latencytarget:http_server_requests_seconds:rate3d > (1 * 0.2)
          for: 3h
          labels:
            job: planetarium-app
            severity: warning
