{
 "title": "Blue/Green Deployment",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "jobs", "label": "Deployment", "query": { "query": "label_values(job)" } },
   {
    "name": "loki_jobs",
    "label": "Loki Jobs",
    "query": {}
   },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "loki", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  { "title": "Rate of Change: Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Latency 5mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency:rate5m{job=\"$jobs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 15mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency:rate15m{job=\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Latency 30mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency:rate30m{job=\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Latency 60mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency:rate60m{job=\"$jobs\"}"
    }
   ]
  },
  { "title": "Rate of Change: Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Success Rate 5mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "successrate:rate5m{job=\"$jobs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate 15mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "successrate:rate15m{job=\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Success Rate 30mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "successrate:rate30m{job=\"$jobs\"}"
    }
   ]
  },
  {
   "title": "Success Rate 60mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "successrate:rate60m{job=\"$jobs\"}"
    }
   ]
  },
  { "title": "99th Percentile Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "99 Percentile Latency in 5mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency99:rate5m{job=\"$jobs\"}"
    }
   ]
  },
  {
   "title": "99 Percentile Latency in 15mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency99:rate15m{job=\"$jobs\"}"
    }
   ]
  },
  {
   "title": "99 Percentile Latency in 30mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency99:rate30m{job=\"$jobs\"}"
    }
   ]
  },
  {
   "title": "99 Percentile Latency in 60mins",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "latency99:rate60m{job=\"$jobs\"}"
    }
   ]
  },
  { "title": " Loki", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "ERROR Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"$loki_jobs\"} |= `ERROR`"
    }
   ]
  },
  {
   "title": "WARN Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"$loki_jobs\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "INFO Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"$loki_jobs\"} |= `INFO`"
    }
   ]
  },
  { "title": "Static", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Total Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"$jobs\", outcome!=\"SERVER_ERROR\"}) / sum(http_server_requests_seconds_count{job=\"$jobs\"})"
    }
   ]
  },
  {
   "title": "Total Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_sum{job=\"$jobs\"}) / sum by(uri) (http_server_requests_seconds_count{job=\"$jobs\"})"
    }
   ]
  }
 ]
}